### ISSUE TITLE
Error de Carpeta Home

### ISSUE THREAD

**Issue by EliasNP** [SergioQuijanoRey/dotfiles#1]
Hola Sergio me gusto mucho tu configuración   
solo un detalle por el momento lo acabo de clonar y lo estoy instalando.

Pero veo que en los scripts tienes Carpetas de home como (/home/sergio/...) y en otras recurres a la Variable $HOME  
deberias poner todas con la variable para que la gente con pocos conocimientos pueda copiar tu codigo sin modificar nada  
o al menos poner un aviso para que sustituyan el home por el suyo propio 

si veo algo mñas te aviso.

Un saludo.

**Comment by SergioQuijanoRey** [comment]
Muchas gracias por el comentario, ahora lo miro
